package com.bteconosur.db.util;

/**
 * Claves disponibles para opciones de configuración de jugador.
 */
public enum ConfigurationKey {
    GENERAL_GLOBAL_CHAT_ON_JOIN,
    GENERAL_SIMULTANEOUS_NOTIFICATIONS,
    GENERAL_PAIS_BORDER,
    GENERAL_LABEL_BORDER,
    GENERAL_PROJECT_TITLE,
    GENERAL_DIVISION_TITLE,
    GENERAL_SCOREBOARD,
    REVIEWER_DS_NOTIFICATIONS,
    MANAGER_DS_NOTIFICATIONS,
    SCOREBOARD_ONLINE,
    SCOREBOARD_PLAYER,
    SCOREBOARD_PROYECTO
}
