package com.bteconosur.db.util;

public enum InteractionKey {
    HELP_COMMAND,
    JOIN_PROJECT,
    FINISH_PROJECT,
    CREATE_PROJECT,
    ACCEPT_CREATE_PROJECT,
    REJECT_CREATE_PROJECT,
    FINISH_EDIT_PROJECT,
    REDEFINE_PROJECT,
    ACCEPT_REDEFINE_PROJECT,
    REJECT_REDEFINE_PROJECT,
    DELETE_PROJECT,
    CONFIRMATION,
    GENERIC
}
